<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxJogFD\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxJogFD/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDxJogFD.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDxJogFD\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDxJogFD\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'DxJogFD',
    'container.build_id' => '82976887',
    'container.build_time' => 1539870256,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxJogFD');
